### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by McCracken2020** [LazarQt/LimitedPower.DraftHelperSync#5]
This popped up while running

![image](https://user-images.githubusercontent.com/112828388/188333167-b121a0fc-5a72-4f06-bbec-bebeec6a6658.png)

**Comment by LazarQt** [comment]
Should be fixed with newest release: https://github.com/LazarQt/LimitedPower.DraftHelperSync/releases/tag/1.1.3

Can you confirm that it works?

**Comment by LazarQt** [comment]
I see you replied to the other open issue, which means this should be solved.
